In [4]:
##create a bag of words model with nGram
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "Taj Mahal is beautiful",
    "I love NLP",
    "Machine Learning is amazing"
]

cv = CountVectorizer(max_features=100,
                     binary=True,
                     ngram_range=(1,1))

X = cv.fit_transform(corpus).toarray()

print(X)
print(cv.vocabulary_)


[[0 1 1 0 0 0 1 0 1]
 [0 0 0 0 1 0 0 1 0]
 [1 0 1 1 0 1 0 0 0]]
{'taj': np.int64(8), 'mahal': np.int64(6), 'is': np.int64(2), 'beautiful': np.int64(1), 'love': np.int64(4), 'nlp': np.int64(7), 'machine': np.int64(5), 'learning': np.int64(3), 'amazing': np.int64(0)}


In [2]:
cv.vocabulary_

{'taj': np.int64(8),
 'mahal': np.int64(6),
 'is': np.int64(2),
 'beautiful': np.int64(1),
 'love': np.int64(4),
 'nlp': np.int64(7),
 'machine': np.int64(5),
 'learning': np.int64(3),
 'amazing': np.int64(0)}