In [ ]:
# !pip install gensim

  Using cached gensim-4.4.0-cp310-cp310-win_amd64.whl.metadata (8.6 kB)
  Using cached scipy-1.15.3-cp310-cp310-win_amd64.whl.metadata (60 kB)
  Using cached smart_open-7.6.1-py3-none-any.whl.metadata (25 kB)
  Using cached wrapt-2.2.1-cp310-cp310-win_amd64.whl.metadata (7.6 kB)
Using cached gensim-4.4.0-cp310-cp310-win_amd64.whl (24.4 MB)
Using cached scipy-1.15.3-cp310-cp310-win_amd64.whl (41.3 MB)
Using cached smart_open-7.6.1-py3-none-any.whl (64 kB)
Using cached wrapt-2.2.1-cp310-cp310-win_amd64.whl (80 kB)

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- -------------------

In [ ]:
# %pip install gensim (WORD2VEC library convert text to numbers )
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [6]:
# %pip install gensim-data

import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

vec_king = wv['king']

In [8]:
# %pip install pandas
import pandas as pd
messages = pd.read_csv('SMSSpamCollection.txt', sep='\t', names=["label", "message"])


In [9]:
from nltk.stem import WordNetLemmatizer
lemmatizer =  WordNetLemmatizer()



In [ ]:
# !pip install nltk
import re
import nltk
### nltk.download('stopwords')

In [ ]:
##data preprocessing 
corpus=[]

for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]',' ', messages['message'][i])
    review = review.lower()
    review = review.split()

    review = [lemmatizer.lemmatize(word) for word in review]
    review =' '.join(review)
    corpus.append(review)

     

In [48]:
[[i,j,k] for i,j,k in zip(list(map(len, corpus)), corpus, messages['message']) if i<1]

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

In [12]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [13]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [14]:
simple_preprocess(__doc__)

['automatically',
 'created',
 'module',
 'for',
 'ipython',
 'interactive',
 'environment']

In [15]:
words=[]
for sent in corpus:
    sent_token = sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [16]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [18]:
import gensim 

In [19]:
# train word2vec from scratch 
model = gensim.models.Word2Vec(words)

In [20]:
##to get all the vocabulary
model.wv.index_to_key

['to',
 'you',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'if',
 'will',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'day',
 'ok',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'she',
 'home',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'they',
 'later',
 'please',
 'any',
 'pls',
 'her',
 'ha',
 'did',
 'co',
 'msg',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'night',
 'make',
 'who',
 'here',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'hope

In [21]:
model.corpus_count

5569

In [22]:
model.epochs

5

In [24]:
model.wv.similar_by_word('good')

[('day', 0.9988778829574585),
 ('happy', 0.9986099600791931),
 ('morning', 0.998601496219635),
 ('about', 0.9985795021057129),
 ('all', 0.9984809160232544),
 ('where', 0.9984472990036011),
 ('my', 0.9984360933303833),
 ('well', 0.9984045028686523),
 ('wa', 0.9983950853347778),
 ('not', 0.9983636736869812)]

In [25]:
model.wv['good'].shape

(100,)

In [ ]:
################################------AVGWORD2VEC----------------######################

In [65]:
import numpy as np
def avg_word2vec(doc):
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key], axis=0)

In [26]:
# !pip install tqdm


[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [66]:
from tqdm import tqdm

In [67]:
##apply for entire sentences
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  8%|▊         | 446/5569 [00:00<00:01, 4447.05it/s]c:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\_core\fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\_core\_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5569/5569 [00:01<00:00, 4858.48it/s]


In [68]:
X

[array([-0.18676034,  0.24482933,  0.01430559,  0.10382896,  0.07162151,
        -0.5182571 ,  0.13146207,  0.5533835 , -0.22754201, -0.12094253,
        -0.19867118, -0.4556842 , -0.08369613,  0.03461903,  0.14788865,
        -0.16209665,  0.13596953, -0.3572231 , -0.05033811, -0.52222854,
         0.16465974,  0.25001767,  0.15408538, -0.15542655, -0.13021843,
        -0.04646287, -0.3421794 , -0.20321527, -0.2867777 , -0.01685802,
         0.28942865, -0.02233362,  0.07148608, -0.18090764, -0.22106032,
         0.40328652,  0.03777571, -0.24086526, -0.14152677, -0.41290176,
         0.20338991, -0.2589492 , -0.23187397,  0.0403088 ,  0.25096473,
        -0.01024525, -0.21337509, -0.09768046,  0.10248659,  0.19785103,
         0.14270312, -0.15186323, -0.06174402,  0.07662638, -0.15447685,
         0.17810155,  0.22899756,  0.10490736, -0.32953864,  0.08013713,
        -0.0590291 ,  0.13070044, -0.04222458, -0.1217591 , -0.29998705,
         0.22234096,  0.04577183,  0.15045251, -0.3

In [69]:
len(X)

5569

In [70]:
##independent features
X_new = np.array(X)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5569,) + inhomogeneous part.

In [71]:
# X_new
X_new[0]
# len(X)
# len(X_new)

np.float64(-0.001502417610026896)

In [72]:
X_new.shape

(5569,)

In [ ]:
X_new[0]

()

In [73]:
X[0]

array([-0.18676034,  0.24482933,  0.01430559,  0.10382896,  0.07162151,
       -0.5182571 ,  0.13146207,  0.5533835 , -0.22754201, -0.12094253,
       -0.19867118, -0.4556842 , -0.08369613,  0.03461903,  0.14788865,
       -0.16209665,  0.13596953, -0.3572231 , -0.05033811, -0.52222854,
        0.16465974,  0.25001767,  0.15408538, -0.15542655, -0.13021843,
       -0.04646287, -0.3421794 , -0.20321527, -0.2867777 , -0.01685802,
        0.28942865, -0.02233362,  0.07148608, -0.18090764, -0.22106032,
        0.40328652,  0.03777571, -0.24086526, -0.14152677, -0.41290176,
        0.20338991, -0.2589492 , -0.23187397,  0.0403088 ,  0.25096473,
       -0.01024525, -0.21337509, -0.09768046,  0.10248659,  0.19785103,
        0.14270312, -0.15186323, -0.06174402,  0.07662638, -0.15447685,
        0.17810155,  0.22899756,  0.10490736, -0.32953864,  0.08013713,
       -0.0590291 ,  0.13070044, -0.04222458, -0.1217591 , -0.29998705,
        0.22234096,  0.04577183,  0.15045251, -0.35024992,  0.25

In [52]:
##dependent features(output features)
y = messages[list(map(lambda x: len(x)>0, corpus))]
y = pd.get_dummies(y['label'])
y = y.iloc[:,0].values

In [ ]:
y.shape

(5569,)

In [92]:
X[0].to_numpy().reshape(1,-1)

array([[-0.18676034, -0.16064584, -0.17862843, ..., -0.25346857,
        -0.22587599, -0.2518791 ]], shape=(1, 5569), dtype=float32)

In [94]:
##this is the final independent features 
df = pd.DataFrame()
for i in range(0, len(X)):
    df = pd.concat(
        [df, pd.DataFrame(X[i].to_numpy().reshape(1, -1))], ignore_index=True
    )

KeyError: 100

In [95]:
print(type(X))
print(X.shape)

print(type(X[0]))
print(X[0])

<class 'pandas.core.frame.DataFrame'>
(5569, 101)
<class 'pandas.core.series.Series'>
0      -0.186760
1      -0.160646
2      -0.178628
3      -0.255083
4      -0.218692
          ...   
5564   -0.212572
5565   -0.231236
5566   -0.253469
5567   -0.225876
5568   -0.251879
Name: 0, Length: 5569, dtype: float32


In [82]:
df.head()
# df.shape

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.186760,0.244829,0.014306,0.103829,0.071622,-0.518257,0.131462,0.553384,-0.227542,-0.120943,...,0.247697,0.153214,0.089872,0.139942,0.366482,0.370779,0.170858,-0.229082,0.155614,-0.078404
1,-0.160646,0.209842,0.007812,0.092112,0.055735,-0.454311,0.106254,0.483485,-0.189570,-0.091735,...,0.213858,0.128826,0.075024,0.118879,0.311712,0.311013,0.145319,-0.206537,0.126474,-0.066437
2,-0.178628,0.257329,0.035119,0.131757,0.083064,-0.575233,0.134211,0.566470,-0.243427,-0.132329,...,0.244252,0.164500,0.082651,0.150267,0.380056,0.372492,0.155585,-0.262643,0.184857,-0.085176
3,-0.255083,0.332017,0.010968,0.140075,0.087901,-0.691952,0.175775,0.755103,-0.310324,-0.155146,...,0.336630,0.201808,0.118160,0.192232,0.482171,0.502362,0.232425,-0.314693,0.199701,-0.096057
4,-0.218692,0.279179,0.014713,0.115912,0.086684,-0.586494,0.145557,0.642254,-0.262491,-0.137317,...,0.291228,0.169167,0.103899,0.160477,0.410390,0.426622,0.194453,-0.267973,0.170863,-0.095063


In [87]:
df['Output'] = y


In [88]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,Output
0,-0.186760,0.244829,0.014306,0.103829,0.071622,-0.518257,0.131462,0.553384,-0.227542,-0.120943,...,0.153214,0.089872,0.139942,0.366482,0.370779,0.170858,-0.229082,0.155614,-0.078404,True
1,-0.160646,0.209842,0.007812,0.092112,0.055735,-0.454311,0.106254,0.483485,-0.189570,-0.091735,...,0.128826,0.075024,0.118879,0.311712,0.311013,0.145319,-0.206537,0.126474,-0.066437,True
2,-0.178628,0.257329,0.035119,0.131757,0.083064,-0.575233,0.134211,0.566470,-0.243427,-0.132329,...,0.164500,0.082651,0.150267,0.380056,0.372492,0.155585,-0.262643,0.184857,-0.085176,False
3,-0.255083,0.332017,0.010968,0.140075,0.087901,-0.691952,0.175775,0.755103,-0.310324,-0.155146,...,0.201808,0.118160,0.192232,0.482171,0.502362,0.232425,-0.314693,0.199701,-0.096057,True
4,-0.218692,0.279179,0.014713,0.115912,0.086684,-0.586494,0.145557,0.642254,-0.262491,-0.137317,...,0.169167,0.103899,0.160477,0.410390,0.426622,0.194453,-0.267973,0.170863,-0.095063,True


In [ ]:
# remove null value 
df.dropna(inplace=True)

In [90]:
# check if nullvalue is present or not 
df.isnull().sum()

0         12
1         12
2         12
3         12
4         12
          ..
96        12
97        12
98        12
99        12
Output     0
Length: 101, dtype: int64

In [83]:
# messages.shape

##independent features
X = df

In [84]:
##train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(
    X,y, test_size=0.20
)

In [85]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
1692,-0.242194,0.321047,0.025744,0.142479,0.098711,-0.682059,0.165089,0.718475,-0.293748,-0.162532,...,0.318220,0.198776,0.116072,0.177170,0.472603,0.476920,0.216325,-0.300291,0.214312,-0.101100
885,-0.230360,0.292098,0.017924,0.119148,0.088199,-0.616015,0.148394,0.664241,-0.274051,-0.147605,...,0.303646,0.182061,0.113112,0.165322,0.429533,0.452052,0.199312,-0.271612,0.185395,-0.098650
5157,-0.246942,0.314978,0.012744,0.126410,0.091177,-0.668337,0.160842,0.728232,-0.282479,-0.143421,...,0.326941,0.178801,0.107552,0.166268,0.460503,0.468950,0.209749,-0.305163,0.179619,-0.102621
1059,-0.278707,0.339386,0.021353,0.134860,0.125767,-0.721887,0.166278,0.795519,-0.324096,-0.177393,...,0.376996,0.211289,0.122047,0.186023,0.494838,0.531291,0.220961,-0.342099,0.216309,-0.107205
2378,-0.184163,0.314445,0.014298,0.136793,0.046046,-0.643558,0.185426,0.663988,-0.267121,-0.156118,...,0.260416,0.198785,0.133672,0.180871,0.468958,0.457284,0.227995,-0.230852,0.203181,-0.112699


In [86]:
y_train

array([ True,  True,  True, ...,  True,  True,  True], shape=(4455,))

In [ ]:
##machine learning model
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
